import { Events, Client } from 'discord.js';
import logger from '../services/logger';

const asciiWelcome = `
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMNKOkkkOKNMMMMMWK00000KXWMMMMNXK00000KNWMMMMMWX0O0XWMMMMMWKO0N
W0l,.     .'oKWMMO'.......;dXMWd'. .....':kNMMMO,   ,OMMMMMK; .o
x.  ,oxkxl.  'OWMx. .cxd:.  cNWl   .oxd;  .dWMX:     :XMMMMK,  l
.  :XMMMMWO.  :XMx. .kMMX:  '0Wl   ,0MM0'  :XWd. ;o. .dWMMMK,  l
  .xMMMMMMNc  'OMx. .xNXx.  :XWl.  'ONKl.  oWO' .kNl  'OMMMK,  l
  .kMMMMMMNc  '0Mx.  ...  .cKMWl.   ...  .oXX:  :KNO'  :XMMK,  l
   oWMMMMMK,  ;XMx.  ;llokKWMMWl   .:lldOXWWd.  .''..  .oWM0,  l
;  .oKXNKk;  .kWMx. .kMMMMMMMMWl.  ,0MMMMMM0'  ;llllc'  .OM0,  l
Kl.  ....  .:OWMMx. .kMMMMMMMMWl.  ,KMMMMMXc  :XMMMMMO'  :XK,  l
MWKxolcccoxKWMMMMKdldXMMMMMMMMW0dolkNMMMMMNxloKMMMMMMWOllxXNklo0
0llOWMMMMMMMMMMMMMMMMMMMMMMMMWKkxkKWMMMMMMMMMMMMMMMMMMMMMMMMWOlc
d. :XMMMMMMMMMMMMMMMMMMMMMMMMXc   :XMMMMMMMMMMMMMMMMMMMMMMMMNc  
O. 'OMMMMMMMMMNKKNMMMMMMMMMMMO.   .kWMMMMMMMMMWKO0NMMMMMMMMM0' .
Nl  :XMMMMMMMXl..cKMMMMMMMMMK;     ,0MMMMMMMMMO, .dWMMMMMMMXc  c
MK:  :KWMMMMMWOllkNMMMMMMMWO,  :dc. 'kNMMMMMMMNOdxKMMMMMMWKc  ;K
MMXl. .oKWMMMMMMMMMMMMMMNO:. .dNMNx' .;kXWMMMMMMMMMMMMMWKo. .cKM
MMMWO;. .;okKXNWWWNNKOxc'  .lKWMMMWKo'  .cdOKXNNWNNX0ko;. .;kNMM
MMMMMW0o,.  ..',,,'..  .':xXWMMMMMMMMXkc'.  ..'''''..  .,o0NMMMM
MMMMMMMMWKkdlc:;;;:clox0NWMMMMMMMMMMMMMMNKkdlc::;;:cldkKWMMMMMMM
MMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
`;

export default {
    name: Events.ClientReady,
    once: true,
    execute(client: Client): void {
		logger.debug(asciiWelcome);
		logger.debug('Bot está listo y conectado a Discord.');
		logger.debug(`ID del bot: ${client.user?.id}`);
    },
};