version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: ["node", "main.js"]

  deploy-commands:
    build: .
    env_file:
      - .env
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    entrypoint: ["node", "src/scripts/deploy-commands.js"]

  test:
    build: .
    container_name: discord-bot-test
    env_file:
      - .env
    working_dir: /usr/src/app
    command: ["npm", "run", "test:ci"]