.PHONY: build test test-docker deploy full-deploy

build:
	docker-compose build

launch:
	docker-compose up --build -d

test:
	npm test

test-docker:
	docker-compose run --rm test

deploy: test-docker
	docker-compose run --rm deploy-commands node src/scripts/deploy-commands.js

full-deploy: build deploy
